### ISSUE TITLE
Compile From Windows

### ISSUE THREAD

**Issue by jiayaozhang** [HTDerekLiu/surface_multigrid_code#1]
I am trying to compile the code from windows, shows the below errors

* From `mg_VCycle.cpp and min_quad_with_fixed_mg.cpp` , it shows error like CS3083 "__1" :: left symbols must the a type and C2039 "__1" is not a member from "std"

* MPI is an undefined symbol

Then I fix with

* Delete all the "__1" in `mg_VCycle.cpp and min_quad_with_fixed_mg.cpp`
* Add “_USE_MATH_DEFINES” in  " Property—>C/C++—>Preprocessor—>Preprocessor***"

Then it works!

Now I plan to use this method for some real-time game demos if it works i will update it here again

**Comment by HTDerekLiu** [comment]
Thank you Jiayao for this super useful information!! I didn't test the compilation on Windows machine before. Sorry for causing you issues. Looking forward to hearing any updates :)

**Comment by jiayaozhang** [comment]
For Real-time games, simplification is very important.

1. I have tried to implement the `Spectral Coarsening of Geometric Operators` and `Chordal Decomposition for Spectral Coarsening`. But found that these methods can not get the ideal mesh obj for usage afer i write `writeOBJ("Boots_Simplified.obj")`

```python
% parameters
fMapSize = 100; % size of functional map
numNc = 500; % number of coarse points
lr = 2e-2; % learning rate
decayIter = 1; % learning rate decay iterations (it is optional, just for fine tune the result)
stallIter = 5; % stalling iteration 

% read mesh
[V,F] = readOBJ('./bunny.obj');
V = normalizeUnitArea(V,F);

% construct an initial operator and mass matrix
L = -cotmatrix(V,F);
M = massmatrix(V,F);

% algebraic coarsening
% note: this matlab implementation does not implement the sparse gradient in the 
% appendix A of "Spectral Coarsening of Geometric Operators" [Liu et al. 2019].
% Thus it would be much slower than C++ implementation.
[Lc, Mc, G, P, Cpt] = algebraicCoarsening(L, M, numNc, ...
    'lr', lr, 'decayIter', decayIter, 'stallIter', stallIter);
```

![image](https://user-images.githubusercontent.com/38579506/222661120-f9840fd0-d4fd-40fa-be50-9ce945eea5f5.png)

And then I read the paper again and found that it has already shown in the Limitations & Future works. So i guess it might not generate the mesh at this time.

> 5 LIMITATIONS & FUTURE WORK
> Reconstructing a valid mesh from our output coarsened operator would enable more downstream applications.


Since Unreal Engine only use 1997 QEM methods for simplication which has a lot of disadvantages as shown in papers like `Surface multigrid `and `Spectral Mesh Simplication`. I am wondering if it is feasible for me to change the Unreal Engine's source codes from Quadrics to your methods in the following steps.

1. when solving the QEM，add multi-grid for speed up and increase the correctness as shown in `Surface Multigrid via Intrinsic Prolongation`

```cpp
#include "mg_precompute.h"

// Build up a multi-level hierarchy for the surface multi grid solver
//
// Inputs:
//   Vf    #Vf-by-3 input vertex positions 
//   Ff    #Ff-by-3 input triangle indices
//   ratio  decimation rate between levels
//   nVCoarset  desired number of output faces for the coarsest level
//   dec_type decimation type (0:q-slim, 1:midpoint, 2:vertex removal)
// Outputs:
//   mg    a vector that contains precomputed information for each level

void mg_precompute(
	const Eigen::MatrixXd & Vf,
	const Eigen::MatrixXi & Ff,
	const float & ratio,
	const int & nVCoarsest,
	const int & dec_type,
  	std::vector<mg_data> & mg)
```
 
2. And use the Laplace-Beltrami  LOWPASS method to replace Quadrics QEM as shown in `Spectral Mesh Simplification`


![2](https://user-images.githubusercontent.com/38579506/211568252-7f2b5756-053f-4e1f-a12c-d3151f08e42a.png)

 I hope to package my game not only  in PC, but also mobile. Currently the assets are too large and currently UE QEM simplication method is not perfect, I am wondering if the following 2 steps (multi-grid + LOWPASS) could be feasible and reliable for me to greatly increase the mesh quality. Words fail me to express my gratitude! 🙌🎁

**Comment by HTDerekLiu** [comment]
Hi, I really appreciate you read through those papers in such a detail :) I would say the answer to your question boils down to how you define "mesh quality". 

- QEM, despite existing for quite some time, it is still a very beautiful method if the "mesh quality" is about preserving the appearance for visualization purposes. If rendering and visualizing assets in the game is your main purpose (judging from "Real-time games" you mentioned), I would still think QEM is a very nice solution.
- LOWPASS on the other hand focuses on preserving the spectral properties of the shape. It is mainly designed for accelerating some applications that involves, for instance, using eigenvalues/eigenvectors of the Laplace operator. So if spectral properties is the "mesh quality" you cared about, then that will be a way to go.
- Multigrid is actually not a new mesh simplification, but a technique that can complement QEM, LOWPASS, and other simplification methods. The main focus is give you a way to transfer signals back and forth across meshes in different resolutions, independent to the simplification method you choose. And actually, in the Fig 13 of the paper, we are still using QEM/QSlim as one of our go-to methods for decimation. So you can perceive it as a method that can make QEM more powerful for computation purposes, instead of a new mesh simplification technique.

Besides these techniques, there are also many other methods that are designed for different "mesh qualities" (such as nicely shaped triangles, textures, etc). Thus it is a bit difficult to conclude whether your proposal could be a feasible solution to increase "mesh quality" without first defining which quality you care the most. It would be nice to first clarify that first, and then decide which simplification method to use. Hope this could help!

**Comment by zhuzhiwei99** [comment]
when I compile the code on my ubuntu system, I also met the problem that " error: ‘std::__1’ has not been declared". I don't know why the author wrote code like this. What's the meaning of that?
I fix it by deleting all the "::__1" in mg_VCycle.cpp and min_quad_with_fixed_mg.cpp.

**Comment by HTDerekLiu** [comment]
Thanks for pointing out the issue. Those `::__1` are used to templating these functions on MacOS. We are glad to see that you have a solution to make it work on Ubuntu.

**Comment by jiayaozhang** [comment]
After testing at least five times on four branches of source codes, I make it out, and "Mesh Quality" defines from two different perspectives.

* Focus on Physics, like simple or complex collisions, mainly affect the playing experience.
* Focus on Rendering, like visualizing or detail preserving, mainly affects the visual views.

* From the Physics perspective of Mesh Qualify, I modify mainly from here
https://colin97.github.io/CoACD, using their novel collision-aware concavity metric to simplify the meshes, which could also support delicate and efficient object interaction and manipulation.

* From the Rendering perspective of Mesh Quality, I modify mainly from https://advances.realtimerendering.com/s2021/Karis_Nanite_SIGGRAPH_Advances_2021_final.pdf (The 46/155 page). Therefore they could auto-compute the LOD Distance for each LOD mesh using the QEM around Recursion 10~25 times. 

Hence, each mesh owns two different assets for the gaming pipelines. Therefore, some assets even they have decreased to 1K tri from original 80000 tri and still have high detail preserving and not affect the playing experience too!

Thanks for ideas sharing and spreading! And finally the sum triangles decrease to 8% of the original triangles from the whole mesh models.

**Comment by HTDerekLiu** [comment]
Thanks for sharing the thoughts and conclusions! It is inspiring to learn that you end up keeping two assets, one for physics and one for rendering :)
